name = "__LIB_NAME__"
version = "0.1.0"
defaultTargets = ["__LIB_NAME__", "Unproved"]

[[lean_lib]]
name = "__LIB_NAME__"

[[lean_lib]]
name = "Unproved"

[[require]]
name = "mathlib"
path = "../submodules/mathlib"

[[require]]
name = "REPL"
path = "../submodules/repl"
