"""Build the published blueprint from the Markdown vault.

The vault stays the source of truth. This module writes a *derived* copy in
which every node page is wrapped in a numbered statement box carrying its
derived status, a link to the Lean code that discharges it, and its place in
the DAG -- the presentation ``leanblueprint`` gives a LaTeX blueprint, driven
from Markdown instead.
"""

from __future__ import annotations

import html
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import unquote, urlsplit

from . import mermaid, status
from .graph import Graph, Node, load_graph
from .lean import SourceLinker, build_linker, declaration_names
from .status import is_definition

_HEADING = re.compile(r"^ {0,3}(#{1,6})[ \t]+(.+?)[ \t]*#*[ \t]*$")
_FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
_MARKDOWN_LINK = re.compile(r"(?<!!)\[(?P<label>[^\]]*)\]\(\s*(?P<target>[^)\s]+)(?:\s+[^)]*)?\)")
_DEPENDENCY_SECTIONS = frozenset({"depends on", "proof depends on"})
_SKIPPED_DIRECTORIES = frozenset({".obsidian", ".trash", ".git"})
#: Derived views this command rewrites; stale copies must not leak into the site.
_GENERATED_FILES = frozenset({"dependencies.md", "dependencies.html", "graph.html"})

#: How a ``declaration:`` value is announced in the statement box.
DECLARATION_LABELS = {
    "abbrev": "Abbreviation",
    "axiom": "Axiom",
    "class": "Class",
    "corollary": "Corollary",
    "def": "Definition",
    "definition": "Definition",
    "example": "Example",
    "inductive": "Inductive",
    "instance": "Instance",
    "lemma": "Lemma",
    "proposition": "Proposition",
    "structure": "Structure",
    "theorem": "Theorem",
}

STYLESHEET = "stylesheets/blueprint.css"
MERMAID_SCRIPT = "javascripts/blueprint-mermaid.js"

#: Loose security is required for Mermaid's ``click`` links to work. The diagram
#: is generated from the project's own blueprint, so there is no third-party
#: content in it.
_MERMAID_INIT = """/* Generated by autoform render. Edits are overwritten. */
mermaid.initialize({ startOnLoad: true, securityLevel: "loose", theme: "neutral" });
"""


@dataclass(slots=True)
class RenderReport:
    """What a render produced, and what it could not resolve."""

    output_dir: Path
    pages: int = 0
    nodes: int = 0
    linked: int = 0
    unresolved: list[str] = field(default_factory=list)


def render_site(
    blueprint_dir: str | Path,
    output_dir: str | Path,
    *,
    lean_root: str | Path | None = None,
    repository_url: str | None = None,
    ref: str | None = None,
    clean: bool = True,
) -> RenderReport:
    """Write the published form of *blueprint_dir* into *output_dir*."""
    blueprint = Path(blueprint_dir).expanduser().resolve()
    destination = Path(output_dir).expanduser().resolve()
    if destination == blueprint:
        raise ValueError("refusing to render a blueprint over itself")

    graph = load_graph(blueprint)
    statuses = status.derive(graph)
    linker = build_linker(
        lean_root if lean_root is not None else blueprint.parent,
        repository_url=repository_url,
        ref=ref,
    )
    numbers = _number_nodes(graph)
    used_by = _reverse_edges(graph)

    if clean and destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)

    report = RenderReport(output_dir=destination)
    node_paths = {node.path.resolve(): node for node in graph.nodes.values()}
    # Nodes are published as environments on their milestone page, the way a
    # blueprint chapter carries many statements in sequence. Each keeps an
    # anchor so every cross-reference still lands on the statement itself.
    groups = _group_nodes(graph)
    anchors = {
        node_id: _anchor(node_id, group)
        for group, node_ids in groups.items()
        for node_id in node_ids
    }
    group_pages = {group: destination / _group_page(group) for group in groups}
    targets = {
        node_id: (group_pages[group], anchors[node_id])
        for group, node_ids in groups.items()
        for node_id in node_ids
    }
    node_sources = {
        node.path.resolve(): node_id for node_id, node in graph.nodes.items()
    }

    for source in sorted(blueprint.rglob("*")):
        relative = source.relative_to(blueprint)
        if _SKIPPED_DIRECTORIES.intersection(relative.parts):
            continue
        if relative.name in _GENERATED_FILES:
            continue
        target = destination / relative
        # Directories are created on demand below, so a directory holding
        # nothing but absorbed nodes leaves no empty shell behind.
        if source.is_dir():
            continue
        # A node file no longer becomes a page of its own.
        if source.resolve() in node_paths:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.suffix.lower() == ".md":
            rewritten = _rewrite_links(
                source.read_text(encoding="utf-8"),
                source_dir=source.parent,
                page=target,
                blueprint=blueprint,
                destination=destination,
                node_sources=node_sources,
                targets=targets,
            )
            target.write_text(rewritten, encoding="utf-8")
        else:
            shutil.copy2(source, target)
        report.pages += 1

    for group, node_ids in groups.items():
        page = group_pages[group]
        page.parent.mkdir(parents=True, exist_ok=True)
        narrative = page.read_text(encoding="utf-8") if page.is_file() else None
        chapter, linked, unresolved = _render_chapter(
            group,
            node_ids,
            graph=graph,
            statuses=statuses,
            numbers=numbers,
            used_by=used_by,
            linker=linker,
            page=page,
            targets=targets,
            narrative=narrative,
            blueprint=blueprint,
            destination=destination,
            node_sources=node_sources,
        )
        page.write_text(chapter, encoding="utf-8")
        if narrative is None:  # a milestone with no narrative page of its own
            report.pages += 1
        report.nodes += len(node_ids)
        report.linked += linked
        report.unresolved.extend(unresolved)

    graph_page = destination / "dependencies.md"
    graph_page.write_text(
        mermaid.render_page(
            graph,
            statuses,
            graph_page,
            links=_anchored_links(targets, graph_page),
        ),
        encoding="utf-8",
    )
    report.pages += 1

    for relative, contents in ((STYLESHEET, _stylesheet()), (MERMAID_SCRIPT, _MERMAID_INIT)):
        asset = destination / relative
        asset.parent.mkdir(parents=True, exist_ok=True)
        asset.write_text(contents, encoding="utf-8")
    return report


def _group_nodes(graph: Graph) -> dict[str, list[str]]:
    """Group nodes by milestone, keeping each group in dependency order.

    A node's milestone is the first path segment of its id, so
    ``infimum-loss/theorems/supervision-recovery`` publishes under
    ``infimum-loss``. Nodes sitting directly in ``roadmap/`` share the roadmap
    index page.
    """
    groups: dict[str, list[str]] = {}
    for node_id in status.topological_order(graph):
        head, separator, _ = node_id.partition("/")
        groups.setdefault(head if separator else "", []).append(node_id)
    return groups


def _group_page(group: str) -> Path:
    """Where a milestone's consolidated chapter lives in the output tree."""
    return Path("roadmap") / group / "README.md" if group else Path("roadmap/README.md")


def _anchor(node_id: str, group: str) -> str:
    """A stable in-page anchor for a node, unique within its chapter."""
    remainder = node_id[len(group) + 1 :] if group else node_id
    return remainder.replace("/", "-")


def _anchored_links(
    targets: dict[str, tuple[Path, str]],
    page: Path,
    *,
    extension: str = ".html",
) -> dict[str, str]:
    """Link every node to its statement on the published chapter page.

    Use ``.md`` for links MkDocs will parse -- it validates and rewrites those
    itself -- and ``.html`` for raw HTML and Mermaid, which it never sees. A
    statement on the current page is just a fragment.
    """
    resolved_page = page.resolve()
    links: dict[str, str] = {}
    for node_id, (target, anchor) in targets.items():
        if target.resolve() == resolved_page:
            links[node_id] = f"#{anchor}"
        else:
            href = mermaid.relative_link(target, page, extension)
            if extension == ".html":
                href = _as_published(href)
            links[node_id] = f"{href}#{anchor}"
    return links


def _as_published(href: str) -> str:
    """MkDocs serves ``README.md`` as ``index.html``.

    Links it parses are rewritten for us, but raw HTML and Mermaid fences never
    reach it, so those have to name the published file themselves.
    """
    path = Path(href)
    if path.name.lower() in {"readme.html", "index.html"}:
        return (path.parent / "index.html").as_posix()
    return href


def _rewrite_links(
    text: str,
    *,
    source_dir: Path,
    page: Path,
    blueprint: Path,
    destination: Path,
    node_sources: dict[Path, str],
    targets: dict[str, tuple[Path, str]],
) -> str:
    """Resolve a page's relative links against where it is being published.

    Two things move. Node files stop being pages once their chapter absorbs
    them, so a link naming one becomes an anchor. And a node's body is hoisted
    out of its own directory onto the chapter page, so its remaining relative
    links have to be recomputed from there.
    """
    anchored = _anchored_links(targets, page, extension=".md")

    def replace(match: re.Match[str]) -> str:
        raw = match.group("target")
        bare = raw[1:-1] if raw.startswith("<") and raw.endswith(">") else raw
        path, separator, fragment = bare.partition("#")
        if not path or urlsplit(path).scheme or path.startswith("/"):
            return match.group(0)
        candidate = (source_dir / unquote(path)).resolve()
        node_id = node_sources.get(candidate)
        if node_id is not None:
            return f"[{match.group('label')}]({anchored[node_id]})"
        if not _is_within(candidate, blueprint):
            return match.group(0)
        published = destination / candidate.relative_to(blueprint)
        moved = mermaid.relative_link(published, page, candidate.suffix)
        return f"[{match.group('label')}]({moved}{separator}{fragment})"

    return _outside_fences(text, lambda line: _MARKDOWN_LINK.sub(replace, line))


def _is_within(path: Path, directory: Path) -> bool:
    try:
        path.relative_to(directory)
    except ValueError:
        return False
    return True


def _outside_fences(text: str, transform) -> str:
    """Apply *transform* to every line that is not inside a code fence."""
    fence: tuple[str, int] | None = None
    out: list[str] = []
    for line in text.splitlines():
        match = _FENCE.match(line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = (marker[0], len(marker))
            elif marker[0] == fence[0] and len(marker) >= fence[1]:
                fence = None
            out.append(line)
            continue
        out.append(line if fence is not None else transform(line))
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def _number_nodes(graph: Graph) -> dict[str, str]:
    """Number nodes per declaration kind in dependency order, as a blueprint does."""
    counters: dict[str, int] = {}
    numbers: dict[str, str] = {}
    for node_id in status.topological_order(graph):
        label = _declaration_label(graph.nodes[node_id])
        counters[label] = counters.get(label, 0) + 1
        numbers[node_id] = f"{label} {counters[label]}"
    return numbers


def _declaration_label(node: Node) -> str:
    return DECLARATION_LABELS.get((node.declaration or "").casefold(), "Node")


def _reverse_edges(graph: Graph) -> dict[str, list[str]]:
    used_by: dict[str, list[str]] = {node_id: [] for node_id in graph.nodes}
    for node in graph.nodes.values():
        for dependency in node.dependencies:
            used_by[dependency].append(node.id)
    return {key: sorted(value) for key, value in used_by.items()}


def _render_chapter(
    group: str,
    node_ids: list[str],
    *,
    graph: Graph,
    statuses: dict[str, status.NodeStatus],
    numbers: dict[str, str],
    used_by: dict[str, list[str]],
    linker: SourceLinker,
    page: Path,
    targets: dict[str, tuple[Path, str]],
    narrative: str | None,
    blueprint: Path,
    destination: Path,
    node_sources: dict[Path, str],
) -> tuple[str, int, list[str]]:
    """Render one milestone as a chapter: its prose, then every statement."""
    links = _anchored_links(targets, page)
    sections: list[str] = []
    linked = 0
    unresolved: list[str] = []

    if narrative is not None:
        sections.append(narrative.rstrip())
    else:
        title = group.replace("-", " ").capitalize() if group else "Roadmap"
        sections.extend(["---", f"kind: roadmap\ntitle: {title}", "---", "", f"# {title}"])

    for node_id in node_ids:
        environment, node_linked, node_unresolved = _render_environment(
            graph.nodes[node_id],
            anchor=targets[node_id][1],
            graph=graph,
            statuses=statuses,
            numbers=numbers,
            used_by=used_by,
            linker=linker,
            links=links,
            page=page,
            blueprint=blueprint,
            destination=destination,
            node_sources=node_sources,
            targets=targets,
        )
        sections.append(environment)
        linked += node_linked
        unresolved.extend(node_unresolved)
    return "\n\n".join(sections) + "\n", linked, unresolved


def _render_environment(
    node: Node,
    *,
    anchor: str,
    graph: Graph,
    statuses: dict[str, status.NodeStatus],
    numbers: dict[str, str],
    used_by: dict[str, list[str]],
    linker: SourceLinker,
    links: dict[str, str],
    page: Path,
    blueprint: Path,
    destination: Path,
    node_sources: dict[Path, str],
    targets: dict[str, tuple[Path, str]],
) -> tuple[str, int, list[str]]:
    node_status = statuses[node.id]
    caption, _, number = numbers[node.id].rpartition(" ")
    statement, remainder = _split_body(node.path.read_text(encoding="utf-8"))
    # The body is leaving its own directory for the chapter page, so its
    # relative links have to be recomputed from the chapter's location.
    statement, remainder = (
        _rewrite_links(
            part,
            source_dir=node.path.parent,
            page=page,
            blueprint=blueprint,
            destination=destination,
            node_sources=node_sources,
            targets=targets,
        )
        for part in (statement, remainder)
    )

    meta, linked, unresolved = _meta_rows(
        node,
        graph=graph,
        statuses=statuses,
        numbers=numbers,
        used_by=used_by,
        linker=linker,
        links=links,
    )

    # amsthm distinguishes the two: a proposition is set in italics, a
    # definition upright. leanblueprint keeps that distinction on the web.
    style = "theorem-style-definition" if is_definition(node) else "theorem-style-plain"
    mark = "✓" if node_status.key in {"fully_proved", "mathlib"} else "●"

    lines = [
        f'<div class="bp-thmwrapper {style} bp-{node_status.key}" '
        f'id="{html.escape(anchor, quote=True)}" markdown="1">',
        '<div class="bp-thmheading">',
        f'<span class="bp-thmcaption">{html.escape(caption)}</span>'
        f'<span class="bp-thmlabel">{html.escape(number)}</span>'
        f'<span class="bp-thmtitle">{html.escape(node.title)}</span>'
        f'<a class="bp-permalink" href="#{html.escape(anchor, quote=True)}">#</a>'
        f'<span class="bp-mark" title="{html.escape(node_status.label, quote=True)}">'
        f'{mark}<span class="bp-mark-label">{html.escape(node_status.label)}</span></span>',
        "</div>",
        '<div class="bp-thmcontent" markdown="1">',
        "",
        statement,
        "",
        "</div>",
    ]
    if remainder:
        lines.extend(['<div class="bp-thmnotes" markdown="1">', "", remainder, "", "</div>"])
    if meta:
        lines.append(meta)
    lines.append("</div>")
    return "\n".join(lines), linked, unresolved


def _meta_rows(
    node: Node,
    *,
    graph: Graph,
    statuses: dict[str, status.NodeStatus],
    numbers: dict[str, str],
    used_by: dict[str, list[str]],
    linker: SourceLinker,
    links: dict[str, str],
) -> tuple[str, int, list[str]]:
    rows: list[tuple[str, str]] = []
    linked = 0
    unresolved: list[str] = []

    if node.lean:
        parts: list[str] = []
        for name in declaration_names(node.lean):
            url = linker.url(name)
            location = linker.location(name)
            code = f"<code>{html.escape(name)}</code>"
            if url:
                parts.append(f'<a class="bp-lean" href="{html.escape(url, quote=True)}">{code}</a>')
                linked += 1
            elif location is not None:
                parts.append(f'{code} <span class="bp-where">{html.escape(location.path.as_posix())}</span>')
                linked += 1
            else:
                parts.append(f'{code} <span class="bp-missing">not found in the Lean sources</span>')
                unresolved.append(f"{node.id}: {name}")
        rows.append(("Lean", " · ".join(parts)))

    def references(node_ids: list[str] | tuple[str, ...]) -> str:
        rendered = []
        for other_id in node_ids:
            other = graph.nodes[other_id]
            label = html.escape(f"{numbers[other_id]} ({other.title})")
            rendered.append(
                f'<a class="bp-ref bp-ref-{statuses[other_id].key}" '
                f'href="{html.escape(links[other_id], quote=True)}">{label}</a>'
            )
        return " · ".join(rendered)

    if node.statement_dependencies:
        rows.append(("Uses", references(node.statement_dependencies)))
    proof_only = [
        other for other in node.proof_dependencies if other not in node.statement_dependencies
    ]
    if proof_only:
        rows.append(("Proof uses", references(proof_only)))
    if used_by[node.id]:
        rows.append(("Used by", references(used_by[node.id])))
    if node.discussion:
        rows.append(("Discussion", _discussion_link(node.discussion, linker)))

    if not rows:
        return "", linked, unresolved
    body = "".join(
        f'<div class="bp-row"><span class="bp-key">{key}</span>'
        f'<span class="bp-value">{value}</span></div>'
        for key, value in rows
    )
    return f'<div class="bp-meta">{body}</div>', linked, unresolved


def _discussion_link(discussion: str, linker: SourceLinker) -> str:
    if discussion.startswith(("http://", "https://")):
        url = discussion
        label = discussion
    elif linker.repository_url and discussion.lstrip("#").isdigit():
        number = discussion.lstrip("#")
        url = f"{linker.repository_url}/issues/{number}"
        label = f"#{number}"
    else:
        return html.escape(discussion)
    return f'<a href="{html.escape(url, quote=True)}">{html.escape(label)}</a>'


def _split_body(text: str) -> tuple[str, str]:
    """Return the node's statement and whatever trailing sections follow it.

    Only the statement belongs inside the theorem environment; ``## Sources``
    and friends are page material that sits after it, the way a blueprint sets
    a statement apart from the prose around it.
    """
    body = _body_without_dependencies(text)
    lines = body.splitlines()
    fence: tuple[str, int] | None = None
    for index, line in enumerate(lines):
        fence_match = _FENCE.match(line)
        if fence_match:
            marker = fence_match.group(1)
            if fence is None:
                fence = (marker[0], len(marker))
            elif marker[0] == fence[0] and len(marker) >= fence[1]:
                fence = None
            continue
        if fence is None and _HEADING.match(line):
            statement = "\n".join(lines[:index]).strip()
            # Many statements now share one chapter page, so a node's own
            # subheadings must not compete with the chapter's structure.
            return statement, _demote_headings("\n".join(lines[index:]).strip())
    return body.strip(), ""


def _demote_headings(text: str) -> str:
    def demote(line: str) -> str:
        heading = _HEADING.match(line)
        if heading is None:
            return line
        level = min(len(heading.group(1)) + 4, 6)
        return f"{'#' * level} {heading.group(2)}"

    return _outside_fences(text, demote)


def _body_without_dependencies(text: str) -> str:
    """Drop the frontmatter, the H1, and the dependency sections.

    The DAG is re-presented in the metadata line, so repeating the raw link
    lists on the page would only duplicate it.
    """
    lines = text.splitlines()
    start = 0
    if lines and lines[0].strip() == "---":
        for index in range(1, len(lines)):
            if lines[index].strip() == "---":
                start = index + 1
                break

    kept: list[str] = []
    skipping = False
    dropped_title = False
    fence: tuple[str, int] | None = None

    for line in lines[start:]:
        fence_match = _FENCE.match(line)
        if fence_match:
            marker = fence_match.group(1)
            if fence is None:
                fence = (marker[0], len(marker))
            elif marker[0] == fence[0] and len(marker) >= fence[1]:
                fence = None
            if not skipping:
                kept.append(line)
            continue
        if fence is not None:
            if not skipping:
                kept.append(line)
            continue

        heading = _HEADING.match(line)
        if heading:
            level = len(heading.group(1))
            name = heading.group(2).strip().casefold()
            if level == 1 and not dropped_title:
                dropped_title = True
                skipping = False
                continue
            if level <= 2:
                skipping = level == 2 and name in _DEPENDENCY_SECTIONS
                if skipping:
                    continue
        if not skipping:
            kept.append(line)
    return "\n".join(kept).strip()


def _stylesheet() -> str:
    """amsthm-style environments, following leanblueprint's rendered blueprint.

    No cards and no dark mode: a plasTeX blueprint is a white document with a
    bold run-in heading and an indented body, italic for propositions and
    upright for definitions. Only the status mark and the content rule carry
    colour.
    """
    rules = "\n".join(
        f".bp-{state.key} .bp-mark {{ color: {state.stroke}; }}\n"
        f".bp-{state.key} .bp-thmcontent {{ border-left-color: {state.fill}; }}\n"
        f".bp-ref-{state.key}::before {{ background: {state.fill}; border-color: {state.stroke}; }}"
        for state in status.STATES
    )
    serif = 'Georgia, "Times New Roman", Times, serif'
    sans = '"Lucida Grande", Arial, Helvetica, sans-serif'
    return f"""/* Generated by autoform render. Edits are overwritten. */
.bp-thmwrapper {{ margin: 1.5rem 0 2rem; }}

.bp-thmheading {{
  display: flex;
  align-items: baseline;
  flex-wrap: wrap;
  font-family: {sans};
  font-weight: 700;
  line-height: 150%;
  color: #24292e;
}}
.bp-thmlabel {{ margin-left: 0.4rem; margin-right: 0.5rem; }}
.bp-thmtitle::before {{ content: "("; }}
.bp-thmtitle::after {{ content: ")"; }}

.bp-permalink {{
  margin-left: 0.5rem;
  font-weight: 400;
  text-decoration: none;
  color: #d1d5da;
  opacity: 0;
  transition: opacity 0.1s ease;
}}
.bp-thmwrapper:hover .bp-permalink {{ opacity: 1; }}
.bp-permalink:hover {{ color: #6a737d; }}

.bp-mark {{ margin-left: auto; font-weight: 400; padding-left: 1rem; }}
.bp-mark-label {{
  margin-left: 0.3rem;
  font-family: {sans};
  font-size: 0.78rem;
  letter-spacing: 0.02em;
  color: #6a737d;
}}

.bp-thmcontent {{
  font-family: {serif};
  font-weight: 400;
  line-height: 1.6;
  margin-left: 1rem;
  padding: 0.15rem 0 0.15rem 1rem;
  border-left: 3px solid #e1e4e8;
}}
.theorem-style-plain > .bp-thmcontent {{ font-style: italic; }}
.theorem-style-definition > .bp-thmcontent {{ font-style: normal; }}
.bp-thmcontent > p:first-child {{ margin-top: 0; }}
.bp-thmcontent > p:last-child {{ margin-bottom: 0; }}

.bp-thmnotes {{
  font: 0.85rem/1.7 {sans};
  margin: 0.6rem 0 0 2rem;
  color: #4a5560;
}}
.bp-thmnotes h6 {{
  font-size: 0.78rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: #6a737d;
  margin: 0.5rem 0 0.15rem;
}}
.bp-thmnotes ul {{ margin: 0; padding-left: 1.1rem; }}

.bp-meta {{
  font: 0.85rem/1.8 {sans};
  margin: 0.6rem 0 0 2rem;
}}
.bp-row {{ display: flex; gap: 0.75rem; }}
.bp-key {{ flex: 0 0 6rem; color: #6a737d; }}
.bp-value {{ flex: 1; }}
.bp-lean {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }}
.bp-where {{ color: #6a737d; }}
.bp-missing {{ color: #b91c1c; }}
.bp-ref::before {{
  content: "";
  display: inline-block;
  width: 0.6rem;
  height: 0.6rem;
  margin-right: 0.35rem;
  border: 1px solid #9aa3b2;
  border-radius: 2px;
}}
.bp-swatch {{
  display: inline-block;
  width: 0.9rem;
  height: 0.9rem;
  border: 1px solid #9aa3b2;
  border-radius: 3px;
  vertical-align: middle;
}}
{rules}
"""


__all__ = [
    "DECLARATION_LABELS",
    "MERMAID_SCRIPT",
    "STYLESHEET",
    "RenderReport",
    "render_site",
]
