"""Build the published blueprint from the Markdown vault.

The vault stays the source of truth. This module writes a *derived* copy in
which every node page is wrapped in a numbered statement box carrying its
derived status, a link to the Lean code that discharges it, and its place in
the DAG -- the presentation ``leanblueprint`` gives a LaTeX blueprint, driven
from Markdown instead.
"""

from __future__ import annotations

import html
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from . import mermaid, status
from .graph import Graph, Node, load_graph
from .lean import SourceLinker, build_linker, declaration_names

_HEADING = re.compile(r"^ {0,3}(#{1,6})[ \t]+(.+?)[ \t]*#*[ \t]*$")
_FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
_DEPENDENCY_SECTIONS = frozenset({"depends on", "proof depends on"})
_SKIPPED_DIRECTORIES = frozenset({".obsidian", ".trash", ".git"})
#: Derived views this command rewrites; stale copies must not leak into the site.
_GENERATED_FILES = frozenset({"dependencies.md", "dependencies.html", "graph.html"})

#: How a ``declaration:`` value is announced in the statement box.
DECLARATION_LABELS = {
    "abbrev": "Abbreviation",
    "axiom": "Axiom",
    "class": "Class",
    "corollary": "Corollary",
    "def": "Definition",
    "definition": "Definition",
    "example": "Example",
    "inductive": "Inductive",
    "instance": "Instance",
    "lemma": "Lemma",
    "proposition": "Proposition",
    "structure": "Structure",
    "theorem": "Theorem",
}

STYLESHEET = "stylesheets/blueprint.css"
MERMAID_SCRIPT = "javascripts/blueprint-mermaid.js"

#: Loose security is required for Mermaid's ``click`` links to work. The diagram
#: is generated from the project's own blueprint, so there is no third-party
#: content in it.
_MERMAID_INIT = """/* Generated by autoform render. Edits are overwritten. */
mermaid.initialize({ startOnLoad: true, securityLevel: "loose", theme: "neutral" });
"""


@dataclass(slots=True)
class RenderReport:
    """What a render produced, and what it could not resolve."""

    output_dir: Path
    pages: int = 0
    nodes: int = 0
    linked: int = 0
    unresolved: list[str] = field(default_factory=list)


def render_site(
    blueprint_dir: str | Path,
    output_dir: str | Path,
    *,
    lean_root: str | Path | None = None,
    repository_url: str | None = None,
    ref: str | None = None,
    clean: bool = True,
) -> RenderReport:
    """Write the published form of *blueprint_dir* into *output_dir*."""
    blueprint = Path(blueprint_dir).expanduser().resolve()
    destination = Path(output_dir).expanduser().resolve()
    if destination == blueprint:
        raise ValueError("refusing to render a blueprint over itself")

    graph = load_graph(blueprint)
    statuses = status.derive(graph)
    linker = build_linker(
        lean_root if lean_root is not None else blueprint.parent,
        repository_url=repository_url,
        ref=ref,
    )
    numbers = _number_nodes(graph)
    used_by = _reverse_edges(graph)

    if clean and destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)

    report = RenderReport(output_dir=destination)
    node_paths = {node.path.resolve(): node for node in graph.nodes.values()}
    # Where each node will live in the output tree, so cross-references resolve
    # against the published site rather than the vault they were copied from.
    rendered_paths = {
        node_id: destination / node.path.resolve().relative_to(blueprint)
        for node_id, node in graph.nodes.items()
    }

    for source in sorted(blueprint.rglob("*")):
        relative = source.relative_to(blueprint)
        if _SKIPPED_DIRECTORIES.intersection(relative.parts):
            continue
        if relative.name in _GENERATED_FILES:
            continue
        target = destination / relative
        if source.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        node = node_paths.get(source.resolve())
        if node is None:
            shutil.copy2(source, target)
            report.pages += 1
            continue
        page, linked, unresolved = _render_node_page(
            node,
            graph=graph,
            statuses=statuses,
            numbers=numbers,
            used_by=used_by,
            linker=linker,
            source=source,
            target=target,
            rendered_paths=rendered_paths,
        )
        target.write_text(page, encoding="utf-8")
        report.pages += 1
        report.nodes += 1
        report.linked += linked
        report.unresolved.extend(unresolved)

    graph_page = destination / "dependencies.md"
    graph_page.write_text(
        mermaid.render_page(
            graph,
            statuses,
            graph_page,
            links=_links_from(rendered_paths, graph_page),
        ),
        encoding="utf-8",
    )
    report.pages += 1

    for relative, contents in ((STYLESHEET, _stylesheet()), (MERMAID_SCRIPT, _MERMAID_INIT)):
        asset = destination / relative
        asset.parent.mkdir(parents=True, exist_ok=True)
        asset.write_text(contents, encoding="utf-8")
    return report


def _links_from(rendered_paths: dict[str, Path], page: Path) -> dict[str, str]:
    """Link every node to its published page, relative to *page*."""
    return {
        node_id: mermaid.relative_link(path, page, ".html")
        for node_id, path in rendered_paths.items()
    }


def _number_nodes(graph: Graph) -> dict[str, str]:
    """Number nodes per declaration kind in dependency order, as a blueprint does."""
    counters: dict[str, int] = {}
    numbers: dict[str, str] = {}
    for node_id in status.topological_order(graph):
        label = _declaration_label(graph.nodes[node_id])
        counters[label] = counters.get(label, 0) + 1
        numbers[node_id] = f"{label} {counters[label]}"
    return numbers


def _declaration_label(node: Node) -> str:
    return DECLARATION_LABELS.get((node.declaration or "").casefold(), "Node")


def _reverse_edges(graph: Graph) -> dict[str, list[str]]:
    used_by: dict[str, list[str]] = {node_id: [] for node_id in graph.nodes}
    for node in graph.nodes.values():
        for dependency in node.dependencies:
            used_by[dependency].append(node.id)
    return {key: sorted(value) for key, value in used_by.items()}


def _render_node_page(
    node: Node,
    *,
    graph: Graph,
    statuses: dict[str, status.NodeStatus],
    numbers: dict[str, str],
    used_by: dict[str, list[str]],
    linker: SourceLinker,
    source: Path,
    target: Path,
    rendered_paths: dict[str, Path],
) -> tuple[str, int, list[str]]:
    node_status = statuses[node.id]
    heading = f"{numbers[node.id]} ({node.title})"
    body = _body_without_dependencies(source.read_text(encoding="utf-8"))

    meta, linked, unresolved = _meta_rows(
        node,
        graph=graph,
        statuses=statuses,
        numbers=numbers,
        used_by=used_by,
        linker=linker,
        links=_links_from(rendered_paths, target),
    )

    return (
        "\n".join(
            [
                "---",
                f"title: {heading}",
                "---",
                "",
                f'<div class="bp-node bp-{node_status.key}" markdown="1">',
                f'<p class="bp-chip">{html.escape(node_status.label)}</p>',
                "",
                f"# {heading}",
                "",
                body.strip(),
                "",
                meta,
                "</div>",
                "",
            ]
        ),
        linked,
        unresolved,
    )


def _meta_rows(
    node: Node,
    *,
    graph: Graph,
    statuses: dict[str, status.NodeStatus],
    numbers: dict[str, str],
    used_by: dict[str, list[str]],
    linker: SourceLinker,
    links: dict[str, str],
) -> tuple[str, int, list[str]]:
    rows: list[tuple[str, str]] = []
    linked = 0
    unresolved: list[str] = []

    if node.lean:
        parts: list[str] = []
        for name in declaration_names(node.lean):
            url = linker.url(name)
            location = linker.location(name)
            code = f"<code>{html.escape(name)}</code>"
            if url:
                parts.append(f'<a class="bp-lean" href="{html.escape(url, quote=True)}">{code}</a>')
                linked += 1
            elif location is not None:
                parts.append(f'{code} <span class="bp-where">{html.escape(location.path.as_posix())}</span>')
                linked += 1
            else:
                parts.append(f'{code} <span class="bp-missing">not found in the Lean sources</span>')
                unresolved.append(f"{node.id}: {name}")
        rows.append(("Lean", " · ".join(parts)))

    def references(node_ids: list[str] | tuple[str, ...]) -> str:
        rendered = []
        for other_id in node_ids:
            other = graph.nodes[other_id]
            label = html.escape(f"{numbers[other_id]} ({other.title})")
            rendered.append(
                f'<a class="bp-ref bp-ref-{statuses[other_id].key}" '
                f'href="{html.escape(links[other_id], quote=True)}">{label}</a>'
            )
        return " · ".join(rendered)

    if node.statement_dependencies:
        rows.append(("Uses", references(node.statement_dependencies)))
    proof_only = [
        other for other in node.proof_dependencies if other not in node.statement_dependencies
    ]
    if proof_only:
        rows.append(("Proof uses", references(proof_only)))
    if used_by[node.id]:
        rows.append(("Used by", references(used_by[node.id])))
    if node.discussion:
        rows.append(("Discussion", _discussion_link(node.discussion, linker)))

    if not rows:
        return "", linked, unresolved
    body = "".join(
        f'<div class="bp-row"><span class="bp-key">{key}</span>'
        f'<span class="bp-value">{value}</span></div>'
        for key, value in rows
    )
    return f'<div class="bp-meta">{body}</div>', linked, unresolved


def _discussion_link(discussion: str, linker: SourceLinker) -> str:
    if discussion.startswith(("http://", "https://")):
        url = discussion
        label = discussion
    elif linker.repository_url and discussion.lstrip("#").isdigit():
        number = discussion.lstrip("#")
        url = f"{linker.repository_url}/issues/{number}"
        label = f"#{number}"
    else:
        return html.escape(discussion)
    return f'<a href="{html.escape(url, quote=True)}">{html.escape(label)}</a>'


def _body_without_dependencies(text: str) -> str:
    """Drop the frontmatter, the H1, and the dependency sections.

    The DAG is re-presented in the statement box footer, so repeating the raw
    link lists on the page would only duplicate it.
    """
    lines = text.splitlines()
    start = 0
    if lines and lines[0].strip() == "---":
        for index in range(1, len(lines)):
            if lines[index].strip() == "---":
                start = index + 1
                break

    kept: list[str] = []
    skipping = False
    dropped_title = False
    fence: tuple[str, int] | None = None

    for line in lines[start:]:
        fence_match = _FENCE.match(line)
        if fence_match:
            marker = fence_match.group(1)
            if fence is None:
                fence = (marker[0], len(marker))
            elif marker[0] == fence[0] and len(marker) >= fence[1]:
                fence = None
            if not skipping:
                kept.append(line)
            continue
        if fence is not None:
            if not skipping:
                kept.append(line)
            continue

        heading = _HEADING.match(line)
        if heading:
            level = len(heading.group(1))
            name = heading.group(2).strip().casefold()
            if level == 1 and not dropped_title:
                dropped_title = True
                skipping = False
                continue
            if level <= 2:
                skipping = level == 2 and name in _DEPENDENCY_SECTIONS
                if skipping:
                    continue
        if not skipping:
            kept.append(line)
    return "\n".join(kept).strip()


def _stylesheet() -> str:
    """Statement-box styling, in the spirit of a plasTeX blueprint."""
    rules = "\n".join(
        f".bp-{state.key} {{ --bp-fill: {state.fill}; --bp-stroke: {state.stroke}; }}\n"
        f".bp-ref-{state.key}::before {{ background: {state.fill}; border-color: {state.stroke}; }}"
        for state in status.STATES
    )
    return f"""/* Generated by autoform render. Edits are overwritten. */
.bp-node {{
  --bp-fill: #ffffff;
  --bp-stroke: #9aa3b2;
  border: 1px solid #d8dee9;
  border-left: 6px solid var(--bp-stroke);
  border-radius: 6px;
  padding: 1rem 1.25rem 0.25rem;
  margin: 1rem 0 2rem;
  background: #fff;
}}
.bp-node h1 {{
  font-family: Georgia, "Times New Roman", serif;
  font-size: 1.35rem;
  margin: 0.15rem 0 0.75rem;
}}
.bp-node > p, .bp-node > ul, .bp-node > ol {{
  font-family: Georgia, "Times New Roman", serif;
  line-height: 1.6;
}}
.bp-chip {{
  display: inline-block;
  margin: 0;
  padding: 0.1rem 0.6rem;
  border: 1px solid var(--bp-stroke);
  border-radius: 999px;
  background: var(--bp-fill);
  font: 600 0.75rem/1.6 ui-sans-serif, system-ui, sans-serif;
  letter-spacing: 0.02em;
  text-transform: lowercase;
  color: #0f172a;
}}
.bp-meta {{
  border-top: 1px solid #e6eaf0;
  margin-top: 1.25rem;
  padding-top: 0.5rem;
  font: 0.85rem/1.7 ui-sans-serif, system-ui, sans-serif;
}}
.bp-row {{ display: flex; gap: 0.75rem; padding: 0.15rem 0; }}
.bp-key {{ flex: 0 0 6.5rem; color: #64748b; font-weight: 600; }}
.bp-value {{ flex: 1; }}
.bp-lean {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }}
.bp-where {{ color: #64748b; }}
.bp-missing {{ color: #b91c1c; }}
.bp-ref::before {{
  content: "";
  display: inline-block;
  width: 0.6rem;
  height: 0.6rem;
  margin-right: 0.35rem;
  border: 1px solid #9aa3b2;
  border-radius: 2px;
  vertical-align: baseline;
}}
.bp-swatch {{
  display: inline-block;
  width: 0.9rem;
  height: 0.9rem;
  border: 1px solid #9aa3b2;
  border-radius: 3px;
  vertical-align: middle;
}}
{rules}

@media (prefers-color-scheme: dark) {{
  .bp-node {{ background: #0f172a; border-color: #26334a; }}
  .bp-chip {{ color: #0f172a; }}
  .bp-meta {{ border-top-color: #26334a; }}
  .bp-key, .bp-where {{ color: #94a3b8; }}
}}
"""


__all__ = [
    "DECLARATION_LABELS",
    "MERMAID_SCRIPT",
    "STYLESHEET",
    "RenderReport",
    "render_site",
]
